"use server";
import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{z}from"zod";import{requireAdmin}from"@/lib/auth/admin";import{fromLosAngelesLocal}from"@/lib/utils/dates";import type{ActionState,BookingStatus}from"@/types/database";
const optional=z.preprocess(v=>v===""?null:v,z.string().trim().nullable());
const schema=z.object({client_id:z.uuid("Choose a client."),service_id:z.uuid("Choose a service."),title:z.string().trim().min(1,"Title is required."),start_local:z.string().min(1,"Start time is required."),end_local:z.string().min(1,"End time is required."),location:optional,status:z.enum(["pending","confirmed","completed","cancelled"]),internal_notes:optional}).refine(v=>new Date(fromLosAngelesLocal(v.end_local))>new Date(fromLosAngelesLocal(v.start_local)),{message:"End time must be after the start time.",path:["end_local"]});
const parse=(f:FormData)=>schema.safeParse({client_id:f.get("client_id"),service_id:f.get("service_id"),title:f.get("title"),start_local:f.get("start_local"),end_local:f.get("end_local"),location:f.get("location"),status:f.get("status"),internal_notes:f.get("internal_notes")});
async function payload(data:z.infer<typeof schema>,supabase:(Awaited<ReturnType<typeof requireAdmin>>)["supabase"]){const{data:service,error}=await supabase.from("services").select("category").eq("id",data.service_id).single();if(error||!service)throw new Error("The selected service is no longer available.");return{client_id:data.client_id,service_id:data.service_id,title:data.title,category:service.category,start_at:fromLosAngelesLocal(data.start_local),end_at:fromLosAngelesLocal(data.end_local),location:data.location,status:data.status,internal_notes:data.internal_notes};}
export async function createBooking(_:ActionState,f:FormData):Promise<ActionState>{const p=parse(f);if(!p.success)return{error:"Please correct the highlighted information.",fieldErrors:p.error.flatten().fieldErrors};const{supabase}=await requireAdmin();let values;try{values=await payload(p.data,supabase)}catch(e){return{error:e instanceof Error?e.message:"Booking could not be saved."}}const{data,error}=await supabase.from("bookings").insert(values).select("id").single();if(error)return{error:`Booking could not be saved: ${error.message}`};revalidatePath("/admin","layout");redirect(`/admin/bookings/${data.id}?success=created`);}
export async function updateBooking(id:string,_:ActionState,f:FormData):Promise<ActionState>{const p=parse(f);if(!p.success)return{error:"Please correct the highlighted information.",fieldErrors:p.error.flatten().fieldErrors};const{supabase}=await requireAdmin();let values;try{values=await payload(p.data,supabase)}catch(e){return{error:e instanceof Error?e.message:"Changes could not be saved."}}const{error}=await supabase.from("bookings").update(values).eq("id",id);if(error)return{error:`Changes could not be saved: ${error.message}`};revalidatePath("/admin","layout");redirect(`/admin/bookings/${id}?success=updated`);}
export async function setBookingStatus(id:string,status:BookingStatus){const{supabase}=await requireAdmin();const{error}=await supabase.from("bookings").update({status}).eq("id",id);if(error)throw new Error(`Status could not be updated: ${error.message}`);revalidatePath("/admin","layout");}
export async function markBookingComplete(id:string){return setBookingStatus(id,"completed")}
