"use client";import{useActionState,useState}from"react";import{useFormStatus}from"react-dom";import Link from"next/link";import type{ActionState,Booking,Client,Service}from"@/types/database";import{formatDateTimeLocal}from"@/lib/utils/dates";
function Submit({edit}:{edit:boolean}){const{pending}=useFormStatus();return <button className="btn" disabled={pending}>{pending?"Saving…":edit?"Save changes":"Create booking"}</button>}
export function BookingForm({booking,clients,services,action,initialClient}:{booking?:Booking;clients:Client[];services:Service[];action:(s:ActionState,d:FormData)=>Promise<ActionState>;initialClient?:string}){const[state,formAction]=useActionState(action,{});const[serviceId,setServiceId]=useState(booking?.service_id??"");const[start,setStart]=useState(booking?formatDateTimeLocal(booking.start_at):"");const[end,setEnd]=useState(booking?formatDateTimeLocal(booking.end_at):"");const err=(n:string)=>state.fieldErrors?.[n]?.[0];return <form action={formAction} className="card panel form-grid">{state.error&&<p className="notice notice-error span-2" role="alert">{state.error}</p>}
  <div className="field"><label htmlFor="client_id">Client *</label><select className="input" id="client_id" name="client_id" defaultValue={booking?.client_id??initialClient??""} required><option value="">Choose a client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.last_name}, {c.first_name}</option>)}</select>{err("client_id")&&<small className="notice-error">{err("client_id")}</small>}<small><Link href="/admin/clients/new" style={{color:"var(--accent)"}}>Create a client first →</Link></small></div>
  <div className="field"><label htmlFor="service_id">Service *</label><select className="input" id="service_id" name="service_id" value={serviceId} onChange={e=>setServiceId(e.target.value)} required><option value="">Choose a service</option>{["photography","music"].map(cat=><optgroup label={cat[0].toUpperCase()+cat.slice(1)} key={cat}>{services.filter(s=>s.category===cat).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</optgroup>)}</select>{err("service_id")&&<small className="notice-error">{err("service_id")}</small>}</div>
  <div className="field span-2"><label htmlFor="title">Booking title *</label><input className="input" id="title" name="title" defaultValue={booking?.title??""} placeholder="e.g. Graduation Session" required/>{err("title")&&<small className="notice-error">{err("title")}</small>}</div>
  <div className="field"><label htmlFor="start_local">Starts * (Pacific time)</label><input className="input" id="start_local" name="start_local" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} required/></div><div className="field"><label htmlFor="end_local">Ends * (Pacific time)</label><input className="input" id="end_local" name="end_local" type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} required/>{err("end_local")&&<small className="notice-error">{err("end_local")}</small>}</div>
  <div className="field"><label htmlFor="location">Location</label><input className="input" id="location" name="location" defaultValue={booking?.location??""} placeholder="Address or studio name"/></div><div className="field"><label htmlFor="status">Status *</label><select className="input" id="status" name="status" defaultValue={booking?.status??"pending"}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div>
  <div className="field span-2"><label htmlFor="internal_notes">Internal notes</label><textarea className="input" id="internal_notes" name="internal_notes" defaultValue={booking?.internal_notes??""}/></div><div className="span-2"><Submit edit={Boolean(booking)}/></div></form>}
